spring:
  application:
    name: zuul
  rabbitmq:
<<<<<<< HEAD
    host: 192.168.64.3
    port: 5672
    username: admin
    password: admin

server:  port: 3001
  
eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#zuul:
#  routes:#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

zuul:
  retryable: true
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
=======
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
    
server:  port: 3001

eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#zuul:
#  routes:#    item-service: /item-serivce/**
#    user-service: /user-serivce/**
#    order-service: /order-serivce/**
    
    
zuul:
  retryable: true

#ribbon:
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
    
management:  endpoints:    web:      exposure:        include: hystrix.stream
    
    
    
    
    
    
    
>>>>>>> branch 'master' of https://github.com/benwang6/sp-config.git
    